# clean base image containing only comfyui, comfy-cli and comfyui-manager
FROM runpod/worker-comfyui:5.10.0-base

# build-time tokens for gated downloads are read from BuildKit secret
# mounts — they are never written to a layer or to image history.
# pass via: docker buildx build --secret id=hf_token,env=HF_TOKEN .

# install custom nodes into comfyui
RUN git clone https://github.com/cubiq/ComfyUI_InstantID /comfyui/custom_nodes/ComfyUI_InstantID && cd /comfyui/custom_nodes/ComfyUI_InstantID && (git checkout 72495e806bc2ab9c41581e15ccaa1bcf83c477e8 2>/dev/null || (git fetch origin 72495e806bc2ab9c41581e15ccaa1bcf83c477e8 --depth=1 && git checkout 72495e806bc2ab9c41581e15ccaa1bcf83c477e8) || echo "WARN: commit 72495e806bc2ab9c41581e15ccaa1bcf83c477e8 unreachable in https://github.com/cubiq/ComfyUI_InstantID, falling back to default branch HEAD")
RUN git clone https://github.com/kijai/ComfyUI-KJNodes /comfyui/custom_nodes/ComfyUI-KJNodes && cd /comfyui/custom_nodes/ComfyUI-KJNodes && (git checkout e0c3fcb388464ffba5ef775bd29e2f793c032ca9 2>/dev/null || (git fetch origin e0c3fcb388464ffba5ef775bd29e2f793c032ca9 --depth=1 && git checkout e0c3fcb388464ffba5ef775bd29e2f793c032ca9) || echo "WARN: commit e0c3fcb388464ffba5ef775bd29e2f793c032ca9 unreachable in https://github.com/kijai/ComfyUI-KJNodes, falling back to default branch HEAD")
RUN git clone https://github.com/Fannovel16/comfyui_controlnet_aux /comfyui/custom_nodes/comfyui_controlnet_aux && cd /comfyui/custom_nodes/comfyui_controlnet_aux && (git checkout 59b1fc411ede8623b2997855b8018f0b3b6cf49f 2>/dev/null || (git fetch origin 59b1fc411ede8623b2997855b8018f0b3b6cf49f --depth=1 && git checkout 59b1fc411ede8623b2997855b8018f0b3b6cf49f) || echo "WARN: commit 59b1fc411ede8623b2997855b8018f0b3b6cf49f unreachable in https://github.com/Fannovel16/comfyui_controlnet_aux, falling back to default branch HEAD")
RUN git clone https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite /comfyui/custom_nodes/ComfyUI-VideoHelperSuite && cd /comfyui/custom_nodes/ComfyUI-VideoHelperSuite && (git checkout 4d907bee61e92c2e65af3bd6383a4e4d356126d1 2>/dev/null || (git fetch origin 4d907bee61e92c2e65af3bd6383a4e4d356126d1 --depth=1 && git checkout 4d907bee61e92c2e65af3bd6383a4e4d356126d1) || echo "WARN: commit 4d907bee61e92c2e65af3bd6383a4e4d356126d1 unreachable in https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite, falling back to default branch HEAD")
RUN git clone https://github.com/cubiq/ComfyUI_IPAdapter_plus /comfyui/custom_nodes/ComfyUI_IPAdapter_plus && cd /comfyui/custom_nodes/ComfyUI_IPAdapter_plus && (git checkout a0f451a5113cf9becb0847b92884cb10cbdec0ef 2>/dev/null || (git fetch origin a0f451a5113cf9becb0847b92884cb10cbdec0ef --depth=1 && git checkout a0f451a5113cf9becb0847b92884cb10cbdec0ef) || echo "WARN: commit a0f451a5113cf9becb0847b92884cb10cbdec0ef unreachable in https://github.com/cubiq/ComfyUI_IPAdapter_plus, falling back to default branch HEAD")
RUN git clone https://github.com/mav-rik/facerestore_cf /comfyui/custom_nodes/facerestore_cf && cd /comfyui/custom_nodes/facerestore_cf && (git checkout ff4d7a5c102441d8f058dd6135797ffb57b6c6ad 2>/dev/null || (git fetch origin ff4d7a5c102441d8f058dd6135797ffb57b6c6ad --depth=1 && git checkout ff4d7a5c102441d8f058dd6135797ffb57b6c6ad) || echo "WARN: commit ff4d7a5c102441d8f058dd6135797ffb57b6c6ad unreachable in https://github.com/mav-rik/facerestore_cf, falling back to default branch HEAD")
RUN git clone https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved /comfyui/custom_nodes/ComfyUI-AnimateDiff-Evolved && cd /comfyui/custom_nodes/ComfyUI-AnimateDiff-Evolved && (git checkout 9257651221002dcba0a12f9cff37e1944e58fb60 2>/dev/null || (git fetch origin 9257651221002dcba0a12f9cff37e1944e58fb60 --depth=1 && git checkout 9257651221002dcba0a12f9cff37e1944e58fb60) || echo "WARN: commit 9257651221002dcba0a12f9cff37e1944e58fb60 unreachable in https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved, falling back to default branch HEAD")

# download models into comfyui
RUN --mount=type=secret,id=hf_token BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN="$(cat /run/secrets/hf_token 2>/dev/null || true)" comfy model download --url 'https://huggingface.co/InstantX/InstantID/resolve/main/ip-adapter.bin' --relative-path models/diffusion_models --filename 'ip-adapter.bin' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN --mount=type=secret,id=hf_token BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN="$(cat /run/secrets/hf_token 2>/dev/null || true)" comfy model download --url 'https://huggingface.co/Comfy-Org/mediapipe/resolve/main/detection/mediapipe_face_fp32.safetensors' --relative-path models/detection --filename 'mediapipe_face_fp32.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN --mount=type=secret,id=hf_token BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN="$(cat /run/secrets/hf_token 2>/dev/null || true)" comfy model download --url 'https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/yzd-v/DWPose/yolox_l.onnx' --relative-path models/annotators --filename 'yolox_l.onnx' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN --mount=type=secret,id=hf_token BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN="$(cat /run/secrets/hf_token 2>/dev/null || true)" comfy model download --url 'https://huggingface.co/hr16/DWPose-TorchScript-BatchSize5/resolve/main/dw-ll_ucoco_384_bs5.torchscript.pt' --relative-path models/annotators --filename 'dw-ll_ucoco_384_bs5.torchscript.pt' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN --mount=type=secret,id=hf_token BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN="$(cat /run/secrets/hf_token 2>/dev/null || true)" comfy model download --url 'https://huggingface.co/CiaraRowles/controlnet-temporalnet-sdxl-1.0/resolve/main/diffusion_pytorch_model.safetensors' --relative-path models/controlnet --filename 'SDXL/controlnet-openpose-sdxl-1.0/diffusion_pytorch_model.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN --mount=type=secret,id=hf_token BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN="$(cat /run/secrets/hf_token 2>/dev/null || true)" comfy model download --url 'https://huggingface.co/CiaraRowles/controlnet-temporalnet-sdxl-1.0/resolve/main/diffusion_pytorch_model.safetensors' --relative-path models/controlnet --filename 'SDXL/instantid/diffusion_pytorch_model.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN --mount=type=secret,id=hf_token BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN="$(cat /run/secrets/hf_token 2>/dev/null || true)" comfy model download --url 'https://huggingface.co/SG161222/RealVisXL_V5.0/resolve/main/RealVisXL_V5.0_fp16.safetensors' --relative-path models/checkpoints --filename 'RealVisXL_V5.0.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN --mount=type=secret,id=hf_token BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN="$(cat /run/secrets/hf_token 2>/dev/null || true)" comfy model download --url 'https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter-plus-face_sdxl_vit-h.safetensors' --relative-path models/ipadapter --filename 'ip-adapter-plus-face_sdxl_vit-h.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN --mount=type=secret,id=hf_token BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN="$(cat /run/secrets/hf_token 2>/dev/null || true)" comfy model download --url 'https://huggingface.co/CiaraRowles/controlnet-temporalnet-sdxl-1.0/resolve/main/diffusion_pytorch_model.safetensors' --relative-path models/controlnet --filename 'SDXL/controlnet-depth-sdxl-1.0/diffusion_pytorch_model.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do comfy model download --url 'https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/codeformer.pth' --relative-path models/facerestore_models --filename 'codeformer.pth' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN --mount=type=secret,id=hf_token BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN="$(cat /run/secrets/hf_token 2>/dev/null || true)" comfy model download --url 'https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors' --relative-path models/clip_vision --filename 'CLIP-ViT-H-14-laion2b-s32b-b79k.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN --mount=type=secret,id=hf_token BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN="$(cat /run/secrets/hf_token 2>/dev/null || true)" comfy model download --url 'https://huggingface.co/guoyww/animatediff/resolve/main/mm_sdxl_v10_beta.ckpt' --relative-path models/animatediff_models --filename 'mm_sdxl_v10_beta.ckpt' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done

# copy all input data (like images or videos) into comfyui (uncomment and adjust if needed)
# COPY input/ /comfyui/input/

# user-provided inputs override the auto-generated placeholders above.
RUN wget --progress=dot:giga -O '/comfyui/input/das.png' "https://cool-anteater-319.convex.cloud/api/storage/cc0f5692-662b-43df-a960-f2f1c2fd0b64"
